test: /home/anton/GB/task1/test
out: /home/anton/GB/task1/out
folder_e: /home/anton/GB/task1/folder_e
folder_x: /home/anton/GB/task1/folder_x
folder_broken: /home/anton/GB/task1/folder_broken

count: 5
bs: 1K
archive_type: 7z

ip: your ip
user: user
passwd: "your password"

pkgname: p7zip-full
file_extension: deb
stat_file: stat.txt

